on:
  push:
    branches:
      - main
name: 🚀 Deploy BODARE and Community MPC Website on push
jobs:
  web-deploy:
    name: 🎉 Deploy  BODARE and Community MPC Server
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: bodarempc.com
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/application/cache/**
          **/application/config/config.php
          **/application/config/database.php
          **/.buildpath/**
          .git-ftp.log
          .project
          .htaccess